language: node_js
node_js: stable
cache: yarn
deploy:
  fqdn: redditpost.ga
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master